version: "3.8"

services:

  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /home/user/docker/grafana-loki/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      traefik_proxy:

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - data:/var/lib/grafana
      - /home/user/docker/grafana-loki/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.nuc10i7fnh.home.arpa`)'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.routers.grafana.tls=true'
      - "traefik.http.routers.grafana.middlewares=authelia@docker,secured@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"


volumes:
  data:


networks:
  traefik_proxy:
    external: true
