services:

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
      - loki_data:/var/lib/loki
    expose:
      - 3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - traefik_proxy
    labels:
      - 'checkmk_monitor=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.loki.rule=Host(`loki.${DOCKER_DOMAIN}`)'
      - 'traefik.http.routers.loki.entrypoints=https'
      - 'traefik.http.routers.loki.tls=true'
      - "traefik.http.routers.loki.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.loki.service=loki"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/roles.yaml:/etc/grafana/provisioning/access-control/roles.yml
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - 'checkmk_monitor=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${DOCKER_DOMAIN}`)'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.routers.grafana.tls=true'
      - "traefik.http.routers.grafana.middlewares=authelia@docker,secured@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"


volumes:
  grafana_data:
  loki_data:

networks:
  traefik_proxy:
    external: true
