services:

  loki:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-xlarge
    image: grafana/loki:latest
    cpu_shares: 128
    volumes:
      - ./loki:/etc/loki
      - loki_data:/var/lib/loki
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    expose:
      - 3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - traefik_proxy
    labels:
      - 'checkmk_monitor=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.loki.rule=Host(`loki.${DOCKER_DOMAIN}`)'
      - 'traefik.http.routers.loki.entrypoints=https'
      - 'traefik.http.routers.loki.tls=true'
      - "traefik.http.routers.loki.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.loki.service=loki"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  grafana:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-medium
    image: grafana/grafana:latest
    cpu_shares: 128
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/roles.yml:/etc/grafana/provisioning/access-control/roles.yml
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards/provider.yaml:/etc/grafana/provisioning/dashboards/provider.yaml:ro
      - ../crabberbot/grafana-dashboard.json:/var/lib/grafana/dashboards/crabberbot.json:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE=/run/secrets/oidc_client_secret
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - traefik_proxy
      - crabberbot
    labels:
      - 'checkmk_monitor=true'
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${DOCKER_DOMAIN}`)'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.routers.grafana.tls=true'
      - "traefik.http.routers.grafana.middlewares=secured@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    secrets:
      - oidc_client_secret


volumes:
  grafana_data:
  loki_data:

networks:
  traefik_proxy:
    external: true
  crabberbot:
    external: true

secrets:
  oidc_client_secret:
    file: secrets/oidc_client_secret
